[rop01_root]
rop01_root_host ansible_host=65.181.125.135 ansible_user=root ansible_ssh_private_key_file=~/.ssh/rop01_key

[rop01_user]
rop01_user_host ansible_host=65.181.125.135 ansible_user=rop01_user ansible_ssh_private_key_file=~/.ssh/rop01_key

[all:vars]
vm_name=rop01
new_user=rop01_user
initial_user=root
